#! /bin/sh

# clean bin/ and obj/ on `bin`, `all` and default
if [ -z "$1" ] || [ "$1" == "bin" ] || [ "$1" == "all" ]; then
    echo "Cleaning bin/"
    rm -rf bin/
    echo "Cleaning obj/"
    rm -rf obj/
fi

# clean makefiles generated by premake on `make` and `all`
if [ "$1" == "make" ] || [ "$1" == "all" ]; then
    echo "Cleaning premake generated files"
    rm -f Makefile Tilize.make
fi

# clean dependencies on `dep`
if [ "$1" == "dep" ]; then
    echo "Cleaning dependencies"
    rm -f src/cJSON.*
    rm -f src/tinycthread.*
    rm -f src/stb*.h
fi

# print help message
if [ "$1" == "help" ] || [ "$1" == "--help" ]; then
    echo "$0       | Remove bin/ and obj/ directories"
    echo "$0 bin   | Same as above"
    echo "$0 make  | Remove makefiles generated by premake"
    echo "$0 all   | Both of the above"
    echo "$0 dep   | Remove downloaded .c and .h files"
    echo "$0 help  | Show this message"
fi
